# Generated by Django 5.2.15 on 2026-09-22 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_iteminventario_stock_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesglosePedidoFlores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.PositiveIntegerField(unique=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Desglose de Flores por Pedido',
                'verbose_name_plural': 'Desgloses de Flores por Pedido',
            },
        ),
        migrations.CreateModel(
            name='DesgloseFlorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desglosado_en', to='inventario.iteminventario')),
                ('desglose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventario.desglosepedidoflores')),
            ],
        ),
    ]
