# Generated by Django 5.2.15 on 2026-09-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_entrega',
            field=models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('SOACHA', 'Recoger en tienda ubicada en Soacha'), ('PLAZA', 'Recoger en Plaza de las Américas')], default='DOMICILIO', max_length=20),
        ),
    ]
