# Generated by Django 5.2.15 on 2026-09-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_detallepedido_acepta_terminos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='acepta_terminos',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='fecha_aceptacion_terminos',
        ),
        migrations.AddField(
            model_name='pedido',
            name='acepta_terminos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_aceptacion_terminos',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
