# Generated by Django 5.2.15 on 2026-09-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='acepta_tratamiento_datos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_aceptacion_tratamiento_datos',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
